### PR TITLE
Spelling corrections in documentation

### PR DESCRIPTION
**Pull request by mark-petersen**
As I read through the documentation, I fixed some spelling mistakes. Thanks for your thorough README file and code comments. I used sed in a bash script to uniformly correct the comments in all the code files.

### CODE REVIEW

**Comment by mrnorman** [comment]
@mark-petersen , Thanks for doing this! That's awesome.

Only request, can we change the YAKL git submodule hash to what it is on current miniWeather main?

**Comment by mrnorman** [comment]
That is, can we set the YAKL hash to 1b940d3 ?

**Comment by mark-petersen** [comment]
Done. Sorry about that. This has no change in the submodule now.

**Comment by mrnorman** [comment]
Thanks again!

**Pull request merged**
